### PR TITLE
Adding guid to generated filename

### PR DESCRIPTION
**Pull request by ewassef**
This will allow the different components to be separated into different projects. This can be helpful in the case where you have the entities in a different project to be published in a nuget package

### CODE REVIEW

**Comment by buehler** [comment]
As by my comment in https://github.com/buehler/dotnet-operator-sdk/discussions/750, shouldn't the addition to the name be deterministic? like the project identifier or the project guid or something?

**Comment by ewassef** [comment]
this wont actually work.. closing

**Comment by buehler** [comment]
Hey @ewassef 
What did not work? I assume the problem still persists?

**Comment by ewassef** [comment]
Ya the way the extension is called isn't letting me chain them from different files. Also, if the entities are referenced externally,  the source generator doesn't look at the referenced assembly symbols (and even if it did, can't get the class declaration needed for the entities array) so it will always generate empty files. 

It will likely be some deeper thought but the simplistic approach I thought it needed didn't work

**Pull request closed without merging**
