### PR TITLE
Adding back API Client

### PR DESCRIPTION
**Pull request by ewassef**
see https://github.com/buehler/dotnet-operator-sdk/discussions/515

### CODE REVIEW

**Comment by ewassef** [comment]
@buehler @georgevella

**Comment by buehler** [comment]
Hey @ewassef

Absolutely, can do :-)

**Comment by buehler** [comment]
You'll need to reorder the property in the implementation and the interface to please the linter.

**Review by buehler — CHANGES_REQUESTED** [review]
You'll need to reorder the property in the implementation and the interface to please the linter.

**Comment by ewassef** [comment]
You got it @buehler

**Review by buehler — CHANGES_REQUESTED** [review]
https://github.com/buehler/dotnet-operator-sdk/actions/runs/4040254178/jobs/6945924553

image

Linter still not happy 😅 
You can build the whole solution locally. If _any_ warning occurs, this is going to be an error in production build. Alternatively, you could build in release config locally to see if it passes or not.

**Review by buehler — APPROVED** [review]

**Pull request merged**
