### PR TITLE
Fix queues not polling when status updated

### PR DESCRIPTION
**Pull request by slacki123**
With reference to https://github.com/buehler/dotnet-operator-sdk/issues/707

This fixes the behaviour of requeues

### CODE REVIEW

**Comment by slacki123** [comment]
initial PR run. I still need to write some tests, which I will do tomorrow

**Comment by slacki123** [comment]
I think it's ready to go. @buehler Could you please have a look?

**Comment by slacki123** [comment]
> Hey @slacki123,
> 
> Thank you! I'll have a look as soon as possible, I'm at a dance festival in Munich right now :)

Rock that swing? :) enjoy

**Comment by buehler** [comment]
Yeah, thank you 😁

**Pull request merged**
