### PR TITLE
Fix #274: Add `selector` to generated deployment

### LINKED ISSUE #274: Generated `Deployment` missing `selector`
**Describe the bug**

A Kubernetes `Deployment` needs a `.spec.selector` so it knows which pods to manage. The [`OperatorGenerator` where this happens](https://github.com/buehler/dotnet-operator-sdk/blob/0fe6c666523199608e9fce5d08a86f71806d12e5/src/KubeOps/Operator/Commands/Generators/OperatorGenerator.cs#L97) is currently missing the `selector`.

**To Reproduce**

1. Create a new controller project.
2. Build and look at the generated `operator/deployment.yaml`.

**Expected behavior**

What you get:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator-deployment: my-controller
  name: operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        operator: my-controller
```

What you _should_ get:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator-deployment: my-controller
  name: operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      operator: my-controller
  template:
    metadata:
      labels:
        operator: my-controller
```

### PR DESCRIPTION
**Pull request by tillig**
Resolves #274 by adding the same labels to `.spec.selector.matchLabels` as are in `.spec.template.metadata.labels`.

As part of this I also added an `.editorconfig` (same one we use for Autofac, but it has some reasonable defaults and matches the current editor style/settings from what I can tell) to ensure contributions will match the repo indent styles, etc. I can nuke that if it's not interesting.

### CODE REVIEW

**Comment by buehler** [comment]
Regarding the `.editorconfig` did you consider the `.DotSettings` file? It is definitely a good addition, if it supports people in contributing to this repo.

**Comment by tillig** [comment]
I didn't add `.DotSettings` because it assumes Visual Studio + ReSharper. I'm on a Mac using Visual Studio Code - no ReSharper, so it wouldn't do anything for me and I couldn't create it anyway. When I'm on a Windows box (rarely, nowadays) I'm a CodeRush guy, not ReSharper, so... still no help. But [`.editorconfig` works with pretty much everything](https://editorconfig.org/#pre-installed) - VS, VS Code, GitHub web editor, Rider, ReSharper, the whole bit. Most times you don't even need an extension, and if you do, it's free.

**Comment by tillig** [comment]
If it turns out you don't want to take the YAML changes, I can update the PR to remove that and just leave the `.editorconfig` if that's interesting.

**Comment by buehler** [comment]
As you wrote, I guess this are pretty much the same settings as I've put into the DotSettings file. So I'm happy to have the editorconfig if it helps other people to contribute.

and for the yaml changes: fine by me ;-)

**Pull request merged**
