### PR TITLE
Remove Self Registration of IServiceProvider

### LINKED ISSUE #210: Compatibility Issue with Autofac
Ran into an interesting issue when using this library with Autofac - the circular dependency detection blows up because you have the service provider registered with itself.

https://github.com/buehler/dotnet-operator-sdk/blob/e8b1b65347de6e5c5711203ad97460684943ce4b/src/KubeOps/Operator/Builder/OperatorBuilder.cs#L168

This issue may or may not be just an Autofac thing, but the same issue has come up and been resolved in MS Orleans (https://github.com/dotnet/orleans/issues/2747). I can't say why this tidbit was originally included, but as noted in the issue on Orleans, both MS DI and Autofac already expose IServiceProvider, so it seems unnecessary.

### PR DESCRIPTION
**Pull request by erin-allison**
Resolves #210

### CODE REVIEW

**Comment by buehler** [comment]
Oh nice catch!
Did not know that they already expose the service provider.

Could you please update the branch? I just tried to merge, but github throws a disturbing message at me: 
image

**Comment by erin-allison** [comment]
Gah, don't merge this just yet... Accidentally pulled a squash merge into my branch and I'm going to clean that up to just rebase my changes

**Comment by buehler** [comment]
I'm going to squash merge anyway...

**Comment by erin-allison** [comment]
In that case I guess it makes no difference. I'll just clean up my fork in the morning then (it's late night for me)

**Pull request merged**
