### PR TITLE
Request body deserialization fix in IAdmissionWebhook 

### LINKED ISSUE #531: [bug]: Mutating WebHook is throwing a Json exception
### Describe the bug

With the latest version the mutating webhook doesn't get called correctly.

Here's the error that it is returning
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMOES899AHEL", Request id "0HMOES899AHEL:0000000B": An unhandled exception was thrown by the application.
      System.Text.Json.JsonException: 'M' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
       ---> System.Text.Json.JsonReaderException: 'M' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
         at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
         at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
         at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
         at System.Text.Json.Utf8JsonReader.Read()
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
         at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
         at k8s.KubernetesJson.Deserialize[TValue](String json)
         at KubeOps.Operator.Webhooks.IAdmissionWebhook`2.<Register>b__15_0(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

I have narrowed it down to

https://github.com/buehler/dotnet-operator-sdk/blob/a0a582d0a6df500e271ae0e154b835df6a7c04aa/src/KubeOps/Operator/Webhooks/IAdmissionWebhook%7BTEntity%2C%20TResult%7D.cs#L110

It is calling ToString on the body stream. This returns the type name, not the actual content of the stream.

### To reproduce

Use the template, 
Create a mutating webhook for a pod
Deploy
Create a pod

### Expected behavior

Not to throw the error and allow the mutating webhook to work

### Screenshots

_No response_

### Additional Context

I also had to modify the resulting dockerfile to reference the 6.0 docker images instead of latest.

### PR DESCRIPTION
**Pull request by tomasfabian**
fixes #531

### CODE REVIEW

**Review by BlowaXD — APPROVED** [review]

**Comment by tomasfabian** [comment]
Hi Christoph @buehler,
could you please have a look on this PR, please? We had to migrate to v7.x.x in order to get [this fix](https://github.com/buehler/dotnet-operator-sdk/issues/522#issuecomment-1418800045), but we stumbled on this new issue which prevents us from fixing our operator.  

Thank you very much!

**Comment by tomasfabian** [comment]
Thank you @buehler for merging this PR! Could you please check the [semantic release,](https://github.com/buehler/dotnet-operator-sdk/actions/runs/4241461611/jobs/7371709206) please?

**Comment by buehler** [comment]
Yeah, I saw that. Already creating a new version  for it...

**Comment by buehler** [comment]
Finally. Version 7.0.3 of the dotnet sdk (7.0.200) changed a flag while creating packages. This lead to errors during build.

**Comment by tomasfabian** [comment]
> Finally. Version 7.0.3 of the dotnet sdk (7.0.200) changed a flag while creating packages. This lead to errors during build.

Thank you very much for you effort Christoph!

**Pull request merged**
